using System.Collections.Generic;

namespace SaigonRide.Services
{
    public interface ILocalizationService
    {
        string Get(string key, string lang = "en");
        Dictionary<string, string> GetAll(string lang = "en");
        string GetStationName(string englishName, string lang = "en");
    }

    public class LocalizationService : ILocalizationService
    {
        private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
        {
            ["en"] = new()
            {
                ["Home"] = "Home",
                ["Rent"] = "Rent",
                ["Return"] = "Return",
                ["Stations"] = "Stations",
                ["Vehicles"] = "Vehicles",
                ["Users"] = "Users",
                ["Admins"] = "Admins",
                ["FindStation"] = "Find a Station",
                ["SelectStationDesc"] = "Select a station to see available vehicles",
                ["StationName"] = "Station Name",
                ["Bikes"] = "Bikes",
                ["EBikes"] = "E-Bikes",
                ["Scooters"] = "Scooters",
                ["Capacity"] = "Capacity",
                ["Action"] = "Action",
                ["ViewVehicles"] = "View Vehicles",
                ["SlotsFree"] = "slots free",
                ["BackToDashboard"] = "Back to Dashboard",
                ["AvailableVehicles"] = "Available Vehicles",
                ["ChangeStation"] = "Change Station",
                ["RentThisBike"] = "Rent This Bike",
                ["RentThisScooter"] = "Rent This Scooter",
                ["All"] = "All",
                ["Rate"] = "Rate",
                ["VndMin"] = "VND/min",
                ["NoVehicles"] = "No vehicles available here!",
                ["SelectAnother"] = "Select Another Station",
                ["SystemStatus"] = "System Status",
                ["Active"] = "Active",
                ["ManageUsers"] = "Manage Users",
                ["ManageVehicles"] = "Manage Vehicles",
                ["ManageStations"] = "Manage Stations",
                ["ViewRentals"] = "View Rentals",
                ["ViewReport"] = "View Report",
                ["TotalUsers"] = "Total Users",
                ["TotalVehicles"] = "Total Vehicles",
                ["TotalStations"] = "Total Stations",
                ["DistributedSystem"] = "Distributed Vehicle Rental System",
                ["WelcomeToSaigonRide"] = "Welcome to SaigonRide",
                ["AdminTitle"] = "Admin:",
                ["LoggedIn"] = "Logged In",
                ["NotLoggedIn"] = "Not Logged In",
                ["LogoutTitle"] = "Logout",
                ["BankNumber"] = "Bank Number",
                ["UserType"] = "Type",
                ["ChosenPayment"] = "Chosen Payment",
                ["TotalPaid"] = "Total Paid",
                ["AdditionalInfo"] = "Additional Info",
                ["Actions"] = "Actions",
                ["LocalCommuter"] = "Local Commuter",
                ["ForeignTourist"] = "Foreign Tourist",
                ["Passport"] = "Passport",
                ["StartNewRental"] = "Start New Rental",
                ["RentalID"] = "Rental ID",
                ["UserID"] = "User ID",
                ["VehicleLabel"] = "Vehicle",
                ["FromStation"] = "From Station",
                ["ToStation"] = "To Station",
                ["StartTime"] = "Start Time",
                ["EndTime"] = "End Time",
                ["Fare"] = "Fare",
                ["Discount"] = "Discount",
                ["FinalFare"] = "Final Fare",
                ["ActiveRental"] = "Active",
                ["Completed"] = "Completed",
                ["Cancelled"] = "Cancelled",
                ["InProgress"] = "In Progress",
                ["EndRental"] = "End Rental",
                ["VehicleDetails"] = "Vehicle Details",
                ["BackToVehicles"] = "Back to Vehicles",
                ["StationDetails"] = "Station Details",
                ["StationID"] = "Station ID",
                ["CapacityChart"] = "Capacity Chart",
                ["VehiclesOutOf"] = "vehicles out of",
                ["BackToStations"] = "Back to Stations",
                ["UserDetails"] = "User Details",
                ["BankAccount"] = "Bank Account",
                ["PaymentMethod"] = "Payment Method",
                ["MoMoEnabled"] = "MoMo Enabled",
                ["VNPayEnabled"] = "VNPay Enabled",
                ["Yes"] = "Yes",
                ["No"] = "No",
                ["ApplePayEnabled"] = "Apple Pay Enabled",
                ["PayPalEnabled"] = "PayPal Enabled",
                ["BackToUsers"] = "Back to Users",
                ["RentalDetails"] = "Rental Details",
                ["RentalInformation"] = "Rental Information",
                ["FareInformation"] = "Fare Information",
                ["StartStation"] = "Start Station",
                ["EndStation"] = "End Station",
                ["CalculatedFare"] = "Calculated Fare",
                ["DiscountApplied"] = "Discount Applied",
                ["BackToRentals"] = "Back to Rentals",
                ["StandardBike"] = "Standard Bike",
                ["EBike"] = "E-Bike",
                ["Scooter"] = "Scooter",
                ["EditStation"] = "Edit Station",
                ["CreateStation"] = "Create Station",
                ["CreateNewStation"] = "Create New Station",
                ["DeleteStation"] = "Delete Station",
                ["DeleteStationConfirm"] = "Are you sure you want to delete this station?",
                ["MaximumCapacity"] = "Maximum Capacity",
                ["CurrentCapacityLabel"] = "Current Capacity",
                ["UpdateStation"] = "Update Station",
                ["Cancel"] = "Cancel",
                ["EditVehicle"] = "Edit Vehicle",
                ["VehicleType"] = "Vehicle Type",
                ["VehicleCode"] = "Vehicle Code",
                ["UpdateVehicle"] = "Update Vehicle",
                ["SelectType"] = "-- Select Type --",
                ["SelectPosition"] = "-- Select Position --",
                ["RentalDuration"] = "Rental Duration (Minutes)",
                ["ConfirmRent"] = "Confirm Rent",
                ["Cash"] = "Cash",
                ["RentalDuration"] = "Rental Duration (Minutes)",
                ["ConfirmRent"] = "Confirm Rent",
                ["Cash"] = "Cash",
                ["SelectUserType"] = "-- Select User Type --",
                ["SelectPaymentMethod"] = "-- Select Payment Method --",
                ["TimeUsed"] = "Time Used",
                ["ScanQRPay"] = "Scan QR code to pay"
            },
            ["vn"] = new()
            {
                ["Home"] = "Trang Chủ",
                ["Rent"] = "Thuê Xe",
                ["Return"] = "Trả Xe",
                ["Stations"] = "Trạm Xe",
                ["Vehicles"] = "Phương Tiện",
                ["Users"] = "Người Dùng",
                ["Admins"] = "Quản Trị",
                ["FindStation"] = "Tìm Trạm Xe",
                ["SelectStationDesc"] = "Chọn một trạm để xem các xe đang có sẵn",
                ["StationName"] = "Tên Trạm",
                ["Bikes"] = "Xe Đạp",
                ["EBikes"] = "Xe Đạp Điện",
                ["Scooters"] = "Xe Máy Điện",
                ["Capacity"] = "Sức Chứa",
                ["Action"] = "Thao Tác",
                ["ViewVehicles"] = "Xem Xe",
                ["SlotsFree"] = "chỗ trống",
                ["BackToDashboard"] = "Về Bảng Điều Khiển",
                ["AvailableVehicles"] = "Xe Hiện Có",
                ["ChangeStation"] = "Đổi Trạm",
                ["RentThisBike"] = "Thuê Xe Này",
                ["RentThisScooter"] = "Thuê Xe Này",
                ["All"] = "Tất Cả",
                ["Rate"] = "Giá Thuê",
                ["VndMin"] = "VNĐ/phút",
                ["NoVehicles"] = "Không có xe nào ở đây!",
                ["SelectAnother"] = "Chọn Trạm Khác",
                // Admin Login
                ["AdminLogin"] = "Đăng Nhập Quản Trị",
                ["Username"] = "Tên Đăng Nhập",
                ["Password"] = "Mật Khẩu",
                ["Login"] = "Đăng Nhập",
                // Return Screen
                ["ReturnVehicle"] = "Trả Xe",
                ["VehicleCode"] = "Mã Xe",
                ["SelectVehicleInTransit"] = "-- Chọn Một Xe Đang Thuê --",
                ["ReturnStation"] = "Trạm Trả Xe",
                ["SelectReturnStation"] = "-- Chọn Trạm Trả Xe --",
                ["AlmostFull"] = "- SẮP ĐẦY",
                ["NoVehiclesInTransit"] = "Không có xe nào đang được thuê.",
                ["PleaseSelectVehicle"] = "Vui lòng chọn một xe để trả.",
                ["PleaseSelectReturnStation"] = "Vui lòng chọn trạm trả xe.",
                ["StationFullCapacity"] = "Trạm đã đầy. Vui lòng chọn trạm khác.",
                ["Back"] = "Quay Lại",
                // Return Result
                ["ReturnResult"] = "Kết Quả Trả Xe",
                ["VehicleReturnedSuccessfully"] = "✓ Xe Được Trả Thành Công",
                ["Success"] = "Thành Công!",
                ["VehicleReturned"] = "Xe của bạn đã được trả lại và xử lý. Hệ thống sẽ tự động quay lại trang chính trong",
                ["Seconds"] = "giây",
                ["Code"] = "Mã Xe",
                ["Status"] = "Trạng Thái",
                ["Returned"] = "✓ Đã Trả",
                ["OriginalCharge"] = "Giá Gốc",
                ["FinalCharge"] = "Giá Cuối Cùng",
                ["Refund"] = "Hoàn Tiền",
                ["ExtraCharge"] = "Phí Thêm",
                ["ReturnToHomeNow"] = "Về Trang Chủ Ngay",
                // Admin Management
                ["Management"] = "Quản Lý",
                ["Reports"] = "Báo Cáo",
                ["StationManagement"] = "Quản Lý Trạm Xe",
                ["AddNewStation"] = "Thêm Trạm Mới",
                ["VehicleManagement"] = "Quản Lý Phương Tiện",
                ["AddNewVehicle"] = "Thêm Xe Mới",
                ["UserManagement"] = "Quản Lý Người Dùng",
                ["AddNewUser"] = "Thêm Người Dùng Mới",
                ["RentalManagement"] = "Quản Lý Cho Thuê",
                ["ID"] = "Mã",
                ["Name"] = "Tên",
                ["Type"] = "Loại",
                ["FarePerMin"] = "Giá/Phút",
                ["CurrentPosition"] = "Vị Trí Hiện Tại",
                ["CurrentMaxCapacity"] = "Sức Chứa Hiện Tại / Tối Đa",
                ["UtilizationRatio"] = "Tỷ Lệ Sử Dụng",
                ["Available"] = "Khả Dụng",
                ["InTransit"] = "Đang Thuê",
                ["Maintenance"] = "Bảo Trì",
                ["View"] = "Xem",
                ["Edit"] = "Sửa",
                ["Delete"] = "Xóa",
                // Report Pages
                ["RevenueReport"] = "Báo Cáo Doanh Thu",
                ["RevenueReportByVehicleCategory"] = "Báo Cáo Doanh Thu Theo Loại Xe",
                ["InventoryReport"] = "Báo Cáo Tồn Kho",
                ["StationInventoryUtilizationReport"] = "Báo Cáo Tồn Kho / Sử Dụng Trạm Xe",
                ["StartDate"] = "Ngày Bắt Đầu",
                ["EndDate"] = "Ngày Kết Thúc",
                ["Filter"] = "Lọc",
                ["TotalRentals"] = "Tổng Số Lần Thuê",
                ["TotalRevenue"] = "Tổng Doanh Thu",
                ["AverageFare"] = "Giá Trung Bình",
                ["TotalDiscountApplied"] = "Tổng Chiết Khấu Áp Dụng",
                ["NoRentalData"] = "Không có dữ liệu cho giai đoạn được chọn.",
                ["SelectedRange"] = "Phạm vi được chọn:",
                ["NotSelected"] = "Chưa chọn",
                ["Low"] = "Thấp",
                ["Medium"] = "Trung Bình",
                ["High"] = "Cao",
                ["LowInventory"] = "Tồn Kho Thấp",
                ["LowInventoryWarning"] = "Cảnh Báo Tồn Kho Thấp: Trạm này có sức chứa dưới 20%. Các xe trả lại tại đây sẽ được giảm giá 15%!",
                ["CapacityVisualization"] = "Biểu Đồ Sức Chứa",
                ["NoInventoryData"] = "Không có dữ liệu tồn kho.",
                ["VehicleType"] = "Loại Xe",
                ["Error"] = "Lỗi",
                ["ValidationErrors"] = "Lỗi Xác Thực:",
                ["LowInventory_Badge"] = "Tồn Kho Thấp",
                ["SystemStatus"] = "Trạng Thái Hệ Thống",
                ["Active"] = "Đang Hoạt Động",
                ["ManageUsers"] = "Quản Lý Người Dùng",
                ["ManageVehicles"] = "Quản Lý Phương Tiện",
                ["ManageStations"] = "Quản Lý Trạm Xe",
                ["ViewRentals"] = "Xem Lượt Thuê",
                ["ViewReport"] = "Xem Báo Cáo",
                ["TotalUsers"] = "Tổng Số Người Dùng",
                ["TotalVehicles"] = "Tổng Số Phương Tiện",
                ["TotalStations"] = "Tổng Số Trạm Xe",
                ["DistributedSystem"] = "Hệ Thống Cho Thuê Xe Phân Tán",
                ["WelcomeToSaigonRide"] = "Chào mừng đến với SaigonRide",
                ["AdminTitle"] = "Quản Trị:",
                ["LoggedIn"] = "Đã Đăng Nhập",
                ["NotLoggedIn"] = "Chưa Đăng Nhập",
                ["LogoutTitle"] = "Đăng Xuất",
                ["BankNumber"] = "Số Tài Khoản",
                ["UserType"] = "Loại Người Dùng",
                ["ChosenPayment"] = "Thanh Toán Đã Chọn",
                ["TotalPaid"] = "Tổng Đã Trả",
                ["AdditionalInfo"] = "Thông Tin Thêm",
                ["Actions"] = "Thao Tác",
                ["LocalCommuter"] = "Người Địa Phương",
                ["ForeignTourist"] = "Khách Du Lịch",
                ["Passport"] = "Hộ Chiếu",
                ["StartNewRental"] = "Bắt Đầu Thuê",
                ["RentalID"] = "Mã Lượt Thuê",
                ["UserID"] = "Mã Người Dùng",
                ["VehicleLabel"] = "Xe",
                ["FromStation"] = "Từ Trạm",
                ["ToStation"] = "Đến Trạm",
                ["StartTime"] = "Thời Gian Bắt Đầu",
                ["EndTime"] = "Thời Gian Kết Thúc",
                ["Fare"] = "Phí",
                ["Discount"] = "Giảm Giá",
                ["FinalFare"] = "Phí Cuối Cùng",
                ["ActiveRental"] = "Đang Diễn Ra",
                ["Completed"] = "Hoàn Thành",
                ["Cancelled"] = "Đã Hủy",
                ["InProgress"] = "Đang Diễn Ra",
                ["EndRental"] = "Kết Thúc Thuê",
                ["VehicleDetails"] = "Chi Tiết Xe",
                ["BackToVehicles"] = "Quay Lại Danh Sách Xe",
                ["StationDetails"] = "Chi Tiết Trạm",
                ["StationID"] = "Mã Trạm",
                ["CapacityChart"] = "Biểu Đồ Sức Chứa",
                ["VehiclesOutOf"] = "xe trên tổng số",
                ["BackToStations"] = "Quay Lại Danh Sách Trạm",
                ["UserDetails"] = "Chi Tiết Người Dùng",
                ["BankAccount"] = "Tài Khoản Ngân Hàng",
                ["PaymentMethod"] = "Phương Thức Thanh Toán",
                ["MoMoEnabled"] = "Đã Kích Hoạt MoMo",
                ["VNPayEnabled"] = "Đã Kích Hoạt VNPay",
                ["Yes"] = "Có",
                ["No"] = "Không",
                ["ApplePayEnabled"] = "Đã Kích Hoạt Apple Pay",
                ["PayPalEnabled"] = "Đã Kích Hoạt PayPal",
                ["BackToUsers"] = "Quay Lại Danh Sách",
                ["RentalDetails"] = "Chi Tiết Cho Thuê",
                ["RentalInformation"] = "Thông Tin Cho Thuê",
                ["FareInformation"] = "Thông Tin Giá Cước",
                ["StartStation"] = "Trạm Bắt Đầu",
                ["EndStation"] = "Trạm Kết Thúc",
                ["CalculatedFare"] = "Giá Cước Tính",
                ["DiscountApplied"] = "Giảm Giá Đã Áp Dụng",
                ["BackToRentals"] = "Quay Lại Danh Sách",
                ["StandardBike"] = "Xe Đạp Thường",
                ["EBike"] = "Xe Đạp Điện",
                ["Scooter"] = "Xe Máy Điện",
                ["EditStation"] = "Sửa Trạm Xe",
                ["CreateStation"] = "Thêm Trạm Xe",
                ["CreateNewStation"] = "Thêm Trạm Mới",
                ["DeleteStation"] = "Xóa Trạm Xe",
                ["DeleteStationConfirm"] = "Bạn có chắc chắn muốn xóa trạm này không?",
                ["MaximumCapacity"] = "Sức Chứa Tối Đa",
                ["CurrentCapacityLabel"] = "Sức Chứa Hiện Tại",
                ["UpdateStation"] = "Cập Nhật Trạm",
                ["Cancel"] = "Hủy",
                ["EditVehicle"] = "Sửa Phương Tiện",
                ["VehicleType"] = "Loại Phương Tiện",
                ["VehicleCode"] = "Mã Xe",
                ["UpdateVehicle"] = "Cập Nhật Phương Tiện",
                ["SelectType"] = "-- Chọn Loại Xe --",
                ["SelectPosition"] = "-- Chọn Vị Trí --",
                ["RentalDuration"] = "Thời Gian Thuê (Phút)",
                ["ConfirmRent"] = "Xác Nhận Thuê",
                ["Cash"] = "Tiền Mặt",
                ["RentalDuration"] = "Thời Gian Thuê (Phút)",
                ["ConfirmRent"] = "Xác Nhận Thuê",
                ["Cash"] = "Tiền Mặt",
                ["SelectUserType"] = "-- Chọn Loại Người Dùng --",
                ["SelectPaymentMethod"] = "-- Chọn Phương Thức Thanh Toán --",
                ["TimeUsed"] = "Thời Gian Đã Thuê",
                ["ScanQRPay"] = "Quét mã QR để thanh toán"
            }
        };

        // Station name translations (English -> Vietnamese)
        private readonly Dictionary<string, string> _stationNames = new()
        {
            ["Ben Thanh Market"] = "Chợ Bến Thành",
            ["District 1 Hub"] = "Trung tâm Quận 1",
            ["Saigon Center"] = "Saigon Centre",
            ["Ben Thanh Central Hub"] = "Trạm Trung tâm Bến Thành",
            ["September 23rd Park Station"] = "Trạm Công viên 23/9",
            ["Ham Nghi Transit Center"] = "Trạm Trung chuyển Hàm Nghi",
            ["Saigon Riverside Station"] = "Trạm Bến Bạch Đằng",
            ["Notre Dame Cathedral Stop"] = "Điểm dừng Nhà thờ Đức Bà",
            ["East Gate Terminal"] = "Bến xe Miền Đông",
            ["West Gate Terminal"] = "Bến xe Miền Tây",
            ["New East City Hub"] = "Bến xe Miền Đông Mới",
            ["An Suong Gateway"] = "Cửa ngõ An Sương",
            ["Saigon Railway Station"] = "Ga Sài Gòn",
            ["University Village Hub"] = "Trạm Làng Đại học",
            ["HCMC Tech Campus Station"] = "Trạm Đại học Bách Khoa",
            ["Economy University Stop"] = "Điểm dừng Đại học Kinh tế",
            ["Agriculture Campus Station"] = "Trạm Đại học Nông Lâm",
            ["Thao Diep Expat Village"] = "Khu dân cư Thảo Điền",
            ["Thao Dien Expat Village"] = "Khu dân cư Thảo Điền",
            ["Phu My Hung Center"] = "Trung tâm Phú Mỹ Hưng",
            ["Tan Son Nhat Airport Station"] = "Trạm Sân bay Tân Sơn Nhất",
            ["Chinatown Terminal"] = "Bến xe Chợ Lớn",
            ["Gia Dinh Park Station"] = "Trạm Công viên Gia Định",
            ["Dam Sen Theme Park Stop"] = "Điểm dừng Công viên Đầm Sen",
            ["In Transit"] = "Đang Thuê",
            ["Maintenance"] = "Bảo Trì",
            ["Unknown"] = "Không Xác Định"
        };

        public string Get(string key, string lang = "en")
        {
            if (!_translations.ContainsKey(lang)) lang = "en";
            return _translations[lang].GetValueOrDefault(key, key);
        }

        public Dictionary<string, string> GetAll(string lang = "en")
        {
            if (!_translations.ContainsKey(lang)) lang = "en";
            return _translations[lang];
        }

        public string GetStationName(string englishName, string lang = "en")
        {
            if (lang == "vn" && _stationNames.ContainsKey(englishName))
                return _stationNames[englishName];
            return englishName;
        }
    }
}
