// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaigonRide.Data;

#nullable disable

namespace SaigonRide.Migrations
{
    [DbContext(typeof(SaigonRideContext))]
    [Migration("20260505071818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaigonRide.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SaigonRide.Models.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<double>("CalculatedFare")
                        .HasColumnType("float");

                    b.Property<double>("DiscountApplied")
                        .HasColumnType("float");

                    b.Property<int>("EndStationId")
                        .HasColumnType("int");

                    b.Property<double>("FinalFare")
                        .HasColumnType("float");

                    b.Property<int>("StartStationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RentalId");

                    b.HasIndex("EndStationId");

                    b.HasIndex("StartStationId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("SaigonRide.Models.RentalTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("EncryptedBankNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedPassport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedVehicleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinutesBorrowed")
                        .HasColumnType("int");

                    b.Property<double>("MoneyRented")
                        .HasColumnType("float");

                    b.Property<DateTime>("RentalStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("StationId");

                    b.ToTable("RentalTransactions");
                });

            modelBuilder.Entity("SaigonRide.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<int>("CurrentCapacity")
                        .HasColumnType("int");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = 1,
                            CurrentCapacity = 3,
                            MaxCapacity = 12,
                            Name = "Ben Thanh Market"
                        },
                        new
                        {
                            StationId = 2,
                            CurrentCapacity = 3,
                            MaxCapacity = 10,
                            Name = "District 1 Hub"
                        },
                        new
                        {
                            StationId = 3,
                            CurrentCapacity = 2,
                            MaxCapacity = 5,
                            Name = "Saigon Center"
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.User", b =>
                {
                    b.Property<string>("BankNum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChosenPaymentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Payed")
                        .HasColumnType("float");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("BankNum");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SaigonRide.Models.Vehicle", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentPos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FarePerMin")
                        .HasColumnType("float");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Code = "SB001",
                            CurrentPos = "Ben Thanh Market",
                            FarePerMin = 500.0,
                            State = 0,
                            Type = "StandardBike"
                        },
                        new
                        {
                            Code = "SB002",
                            CurrentPos = "Ben Thanh Market",
                            FarePerMin = 500.0,
                            State = 0,
                            Type = "StandardBike"
                        },
                        new
                        {
                            Code = "EB001",
                            CurrentPos = "Ben Thanh Market",
                            FarePerMin = 1000.0,
                            State = 0,
                            Type = "EBike"
                        },
                        new
                        {
                            Code = "EB002",
                            CurrentPos = "District 1 Hub",
                            FarePerMin = 1000.0,
                            State = 0,
                            Type = "EBike"
                        },
                        new
                        {
                            Code = "ES001",
                            CurrentPos = "Saigon Center",
                            FarePerMin = 1500.0,
                            State = 0,
                            Type = "Scooter"
                        },
                        new
                        {
                            Code = "ES002",
                            CurrentPos = "District 1 Hub",
                            FarePerMin = 1500.0,
                            State = 0,
                            Type = "Scooter"
                        },
                        new
                        {
                            Code = "ES003",
                            CurrentPos = "Saigon Center",
                            FarePerMin = 1500.0,
                            State = 0,
                            Type = "Scooter"
                        },
                        new
                        {
                            Code = "ES004",
                            CurrentPos = "District 1 Hub",
                            FarePerMin = 1500.0,
                            State = 0,
                            Type = "Scooter"
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.ForeignTourist", b =>
                {
                    b.HasBaseType("SaigonRide.Models.User");

                    b.Property<bool>("P_ApplePay")
                        .HasColumnType("bit");

                    b.Property<bool>("P_PayPal")
                        .HasColumnType("bit");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ForeignTourist");

                    b.HasData(
                        new
                        {
                            BankNum = "INTL001",
                            ChosenPaymentCode = "applepay",
                            Payed = 75000.0,
                            UserType = "ForeignTourist",
                            P_ApplePay = true,
                            P_PayPal = false,
                            Passport = "A12345678"
                        },
                        new
                        {
                            BankNum = "INTL002",
                            ChosenPaymentCode = "paypal",
                            Payed = 150000.0,
                            UserType = "ForeignTourist",
                            P_ApplePay = false,
                            P_PayPal = true,
                            Passport = "B98765432"
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.LocalCommuter", b =>
                {
                    b.HasBaseType("SaigonRide.Models.User");

                    b.Property<bool>("P_MoMo")
                        .HasColumnType("bit");

                    b.Property<bool>("P_VNPay")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("LocalCommuter");

                    b.HasData(
                        new
                        {
                            BankNum = "0123456789",
                            ChosenPaymentCode = "momo",
                            Payed = 50000.0,
                            UserType = "LocalCommuter",
                            P_MoMo = true,
                            P_VNPay = false
                        },
                        new
                        {
                            BankNum = "0987654321",
                            ChosenPaymentCode = "vnpay",
                            Payed = 100000.0,
                            UserType = "LocalCommuter",
                            P_MoMo = true,
                            P_VNPay = true
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.Rental", b =>
                {
                    b.HasOne("SaigonRide.Models.Station", "EndStation")
                        .WithMany("EndStations")
                        .HasForeignKey("EndStationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.Station", "StartStation")
                        .WithMany("StartStations")
                        .HasForeignKey("StartStationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.Vehicle", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndStation");

                    b.Navigation("StartStation");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SaigonRide.Models.RentalTransaction", b =>
                {
                    b.HasOne("SaigonRide.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SaigonRide.Models.Station", b =>
                {
                    b.Navigation("EndStations");

                    b.Navigation("StartStations");
                });

            modelBuilder.Entity("SaigonRide.Models.Vehicle", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
